# Generated by Django 4.0.3 on 2022-03-09 20:18


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("YoutubeAuth", "0001_initial"),
    ]

    def generate_superuser(apps, schema_editor):
        from django.contrib.auth import get_user_model

        User = get_user_model()
        DJANGO_SU_EMAIL = "zod32@me.com"
        DJANGO_SU_PASSWORD = "b554wmrq"

        superuser = User.objects.create_user(
            email=DJANGO_SU_EMAIL,
            password=DJANGO_SU_PASSWORD,
        )
        superuser.is_staff = True
        superuser.is_superuser = True
        superuser.save()

    operations = [
        migrations.RunPython(generate_superuser),
    ]
