# Generated by Django 4.0.3 on 2022-03-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YoutubeAuth', '0002_auto_20220309_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credentials',
            options={},
        ),
        migrations.AlterField(
            model_name='credentials',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='email address'),
        ),
        migrations.AlterUniqueTogether(
            name='credentials',
            unique_together={('email', 'client_id')},
        ),
    ]
