# Generated by Django 4.0.3 on 2022-03-09 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('YoutubeAuth', '0003_alter_credentials_options_alter_credentials_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='credentials',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterUniqueTogether(
            name='credentials',
            unique_together=set(),
        ),
    ]
