# Generated by Django 4.0.3 on 2022-03-10 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YoutubeAuth', '0004_alter_credentials_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='client_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
    ]
