# Generated by Django 4.0.3 on 2022-03-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YoutubeAuth', '0005_alter_credentials_client_id_alter_credentials_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='scopes',
            field=models.JSONField(),
        ),
    ]
