# Generated by Django 4.0.3 on 2022-03-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YoutubeAuth', '0006_alter_credentials_scopes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='scopes',
            field=models.JSONField(blank=True),
        ),
    ]
