# Generated by Django 4.0.3 on 2022-03-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YoutubeSort', '0002_youtubevideo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='artist',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='track',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
