# Generated by Django 4.0.3 on 2022-03-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YoutubeSort', '0003_youtubevideo_artist_youtubevideo_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='artist',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='track',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='yid',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
