# Generated by Django 4.0.3 on 2022-03-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YoutubeSort', '0004_alter_youtubevideo_artist_alter_youtubevideo_track_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='image_url',
            field=models.URLField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
