# Generated by Django 4.0.3 on 2022-03-11 08:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YoutubeSort', '0005_youtubevideo_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
