# Generated by Django 4.0.3 on 2022-03-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YoutubeSort', '0006_youtubevideo_created_at_youtubevideo_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
