# Generated by Django 4.0.3 on 2022-03-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YoutubeSort', '0008_youtubeplaylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubeplaylist',
            name='image_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='youtubeplaylist',
            name='playlist_id',
            field=models.CharField(max_length=255),
        ),
    ]
