# Generated by Django 4.0.3 on 2022-03-18 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YoutubeSort', '0009_alter_youtubeplaylist_image_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtubeplaylist',
            old_name='playlist_id',
            new_name='yt_playlist_id',
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='playlist',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='YoutubeSort.youtubeplaylist'
            ),
            preserve_default=False,
        ),
    ]
