version: '3.9'

services:
  web:
    build:
      context: ./
      dockerfile: YoutubeSort/Dockerfile
    command: tail -f /dev/null #python YoutubeSort/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    working_dir: /code/YoutubeSort
    ports:
      - 8000:8000
    env_file:
      - YoutubeSort/.env.dev
    depends_on:
      - db
      - redis
  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    command: redis-server --loglevel warning --save 60 1
    volumes:
      - redis:/data
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - POSTGRES_DB=django
    ports:
      - "5432:5432"
volumes:
  redis:
    driver: local
  postgres_data: